services:
  rockets-frontend:
    image: rockets-frontend
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    volumes:
      - ./app/:/usr/src/app
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm run dev"]
    networks:
      - app-network
    depends_on:
      - graphql-node

  # Node container
  graphql-node:
    build:
      context: ./graphql
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./graphql:/var/www
    networks:
      app-network:
        aliases:
          - graphql
    working_dir: /var/www
    command: ["sh", "-c", "yarn install && yarn run dev"]

  redis:
    image: redis:latest
    ports:
      - 6379:6379

networks:
  app-network:  # Defining the shared network
    driver: bridge  # This creates a bridge network, the default driver
